name: unearthed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^26.2.4
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  syncfusion_flutter_datepicker: ^26.2.4

flutter:
  uses-material-design: true

  fonts:
      - family: Lovelo
        fonts:
          - asset: assets/fonts/lovelo_black.otf
          # - asset: assets/fonts/league_spartan.otf
          # - asset: assets/fonts/quicksand.otf

  assets:
      - assets/logos/
      - assets/img/new_dresses/
      - assets/img/backgrounds/