name: unearthed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_share: ^2.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^26.2.4
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  country_code_picker: ^3.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  pluralize: ^0.0.8
  flutter_date_range_picker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/uc_icon.png"

flutter:
  uses-material-design: true

  fonts:
      - family: Lovelo
        fonts:
          - asset: assets/fonts/lovelo_black.otf
          # - asset: assets/fonts/league_spartan.otf
          # - asset: assets/fonts/quicksand.otf

  assets:
      - assets/logos/
      - assets/img/new_items/
      - assets/img/backgrounds/