// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmH_YuLFWduaMJ8e0Ggbr1RmnynGbN2mo',
    appId: '1:962384191254:android:a1eecb9356f5740b67ba37',
    messagingSenderId: '962384191254',
    projectId: 'revivals-7697a',
    storageBucket: 'revivals-7697a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO7Gx3VEkWh-ZuJR_EYPgjPIPmxutOSGI',
    appId: '1:962384191254:ios:9b44a79920adfe6167ba37',
    messagingSenderId: '962384191254',
    projectId: 'revivals-7697a',
    storageBucket: 'revivals-7697a.firebasestorage.app',
    iosClientId: '962384191254-hm413sgcmr8e79l0cfhl6eq34sp7n900.apps.googleusercontent.com',
    iosBundleId: 'sg.bluemoon.revivals',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxh6PnMiP6owgZDRr_6aIvtx8E7_Gxjs',
    appId: '1:962384191254:web:0ae28600c4ef2c7f67ba37',
    messagingSenderId: '962384191254',
    projectId: 'revivals-7697a',
    authDomain: 'revivals-7697a.firebaseapp.com',
    storageBucket: 'revivals-7697a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO7Gx3VEkWh-ZuJR_EYPgjPIPmxutOSGI',
    appId: '1:962384191254:ios:e8dfc22ecb3ef2e067ba37',
    messagingSenderId: '962384191254',
    projectId: 'revivals-7697a',
    storageBucket: 'revivals-7697a.firebasestorage.app',
    iosClientId: '962384191254-plkmc7o1cq5ij3m9s890ig0g0bnar53g.apps.googleusercontent.com',
    iosBundleId: 'com.example.unearthed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvxh6PnMiP6owgZDRr_6aIvtx8E7_Gxjs',
    appId: '1:962384191254:web:6437b8f1a4a82e2067ba37',
    messagingSenderId: '962384191254',
    projectId: 'revivals-7697a',
    authDomain: 'revivals-7697a.firebaseapp.com',
    storageBucket: 'revivals-7697a.firebasestorage.app',
  );

}